# Generated by Django 4.0.5 on 2022-07-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_rename_group_title_message_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user_id',
        ),
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Message.group')),
            ],
        ),
    ]
